<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerValcngb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerValcngb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerValcngb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerValcngb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerValcngb\appProdProjectContainer([
    'container.build_hash' => 'Valcngb',
    'container.build_id' => '2092985c',
    'container.build_time' => 1728227518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerValcngb');
