<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEohloqj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEohloqj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEohloqj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEohloqj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEohloqj\appProdProjectContainer([
    'container.build_hash' => 'Eohloqj',
    'container.build_id' => '336f6fa8',
    'container.build_time' => 1728215330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEohloqj');
