services:

  mysql:
    image: mysql:5.7
    #    restart: unless-stopped
    env_file: .env
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7.8
    platform: linux/x86_64
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8888:80
    env_file: .env
    networks:
      - prestashop_network
    volumes:
      - ./prestashop:/var/www/html
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9999:80
    depends_on:
      - mysql
    env_file: .env
    networks:
      - prestashop_network

volumes:
  dbdata:

networks:
  prestashop_network:
